[versions]
alsakt = "0.3.4"
core-ktx = "1.10.1"
junit = "4.13.2"
junit-jupiter-api = "5.9.0"
kotlin-test-junit = "1.9.0"
kotlinx-coroutines-core = "1.7.3"
kotlinx-datetime = "0.4.1"
ktor-io = "2.3.3"
metalava-gradle = "0.2.3"
rtmidi-javacpp = "0.1.3"

[libraries]
alsakt = { module = "dev.atsushieno:alsakt", version.ref = "alsakt" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-api" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-test-junit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-core" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ktor-io = { module = "io.ktor:ktor-io", version.ref = "ktor-io" }
metalava-gradle = { module = "me.tylerbwong.gradle:metalava-gradle", version.ref = "metalava-gradle" }
rtmidi-javacpp = { module = "dev.atsushieno:rtmidi-javacpp", version.ref = "rtmidi-javacpp" }
rtmidi-javacpp-platform = { module = "dev.atsushieno:rtmidi-javacpp-platform", version.ref = "rtmidi-javacpp" }

[plugins]

[bundles]

